import TopNavbar from "./components/TopNavbar";
import "./globals.css";
import localFont from "next/font/local";

// google fonts

import { Inter, Noto_Serif_Bengali, Public_Sans } from "next/font/google";
import SideNavbar from "./components/SideNavbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter-font",
});
// const bgFont = Noto_Serif_Bengali({
//   subsets: ["latin"],
//   display: "swap",
//   weight: "500",
// });

const bFont = localFont({
  src: "../public/font/kalpurush.ttf",
  subsets: ["latin"],
  display: "swap",
  variable: "--bangla-font",
  weight: "400",
});

export const metadata = {
  title: "Al Hadis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bFont.variable} ${inter.variable} bg-white`}>
        <TopNavbar />
        <div className="">
          <SideNavbar />
        </div>
        <div className="ml-[96px] bg-[#f2f4f6] rounded-3xl fixed top-[80px]">
          {children}
        </div>
      </body>
    </html>
  );
}
