import TopNavbar from "./components/TopNavbar";
import "./globals.css";
import localFont from "next/font/local";

// google fonts

import { Inter, Noto_Serif_Bengali, Public_Sans } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter-font",
});
// const bgFont = Noto_Serif_Bengali({
//   subsets: ["latin"],
//   display: "swap",
//   weight: "500",
// });

const bFont = localFont({
  src: "../public/font/kalpurush.ttf",
  subsets: ["latin"],
  display: "swap",
  variable: "--bangla-font",
});

export const metadata = {
  title: "Al Hadis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bFont.variable} ${inter.variable}`}>
        <div>
          <TopNavbar />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
